version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/workdir/src
      - ./tests:/workdir/tests
    environment:
      - DATABASE_URL=file:/workdir/src/infrastructure/prisma/dev.db
      - TEST_DATABASE_URL=file:/workdir/src/infrastructure/prisma/test.db
